/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareJobIdRouteImport } from './routes/share.$jobId'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthRoleRouteImport } from './routes/auth.role'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppEmployerIndexRouteImport } from './routes/_app.employer.index'
import { Route as AppCandidateIndexRouteImport } from './routes/_app.candidate.index'
import { Route as AppEmployerTemplatesRouteImport } from './routes/_app.employer.templates'
import { Route as AppEmployerTalentPoolRouteImport } from './routes/_app.employer.talent-pool'
import { Route as AppEmployerOffersRouteImport } from './routes/_app.employer.offers'
import { Route as AppEmployerJobsRouteImport } from './routes/_app.employer.jobs'
import { Route as AppEmployerCareersRouteImport } from './routes/_app.employer.careers'
import { Route as AppEmployerCandidatesRouteImport } from './routes/_app.employer.candidates'
import { Route as AppEmployerAnalyticsRouteImport } from './routes/_app.employer.analytics'
import { Route as AppCandidateResumeRouteImport } from './routes/_app.candidate.resume'
import { Route as AppCandidatePortfolioRouteImport } from './routes/_app.candidate.portfolio'
import { Route as AppCandidateOnboardingRouteImport } from './routes/_app.candidate.onboarding'
import { Route as AppCandidateNotificationsRouteImport } from './routes/_app.candidate.notifications'
import { Route as AppCandidateJobsRouteImport } from './routes/_app.candidate.jobs'
import { Route as AppCandidateJobHuntRouteImport } from './routes/_app.candidate.job-hunt'
import { Route as AppCandidateInterviewRouteImport } from './routes/_app.candidate.interview'
import { Route as AppCandidateExternalRouteImport } from './routes/_app.candidate.external'
import { Route as AppCandidateCoverLetterRouteImport } from './routes/_app.candidate.cover-letter'
import { Route as AppCandidateCareersRouteImport } from './routes/_app.candidate.careers'
import { Route as AppCandidateAssistantRouteImport } from './routes/_app.candidate.assistant'
import { Route as AppCandidateApplicationsRouteImport } from './routes/_app.candidate.applications'
import { Route as AppEmployerJobsIndexRouteImport } from './routes/_app.employer.jobs.index'
import { Route as AppEmployerJobsNewRouteImport } from './routes/_app.employer.jobs.new'
import { Route as AppEmployerJobsJobIdRouteImport } from './routes/_app.employer.jobs.$jobId'
import { Route as AppCandidateTrainingSessionIdRouteImport } from './routes/_app.candidate.training.$sessionId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareJobIdRoute = ShareJobIdRouteImport.update({
  id: '/share/$jobId',
  path: '/share/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoleRoute = AuthRoleRouteImport.update({
  id: '/auth/role',
  path: '/auth/role',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerIndexRoute = AppEmployerIndexRouteImport.update({
  id: '/employer/',
  path: '/employer/',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateIndexRoute = AppCandidateIndexRouteImport.update({
  id: '/candidate/',
  path: '/candidate/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerTemplatesRoute = AppEmployerTemplatesRouteImport.update({
  id: '/employer/templates',
  path: '/employer/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerTalentPoolRoute = AppEmployerTalentPoolRouteImport.update({
  id: '/employer/talent-pool',
  path: '/employer/talent-pool',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerOffersRoute = AppEmployerOffersRouteImport.update({
  id: '/employer/offers',
  path: '/employer/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerJobsRoute = AppEmployerJobsRouteImport.update({
  id: '/employer/jobs',
  path: '/employer/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerCareersRoute = AppEmployerCareersRouteImport.update({
  id: '/employer/careers',
  path: '/employer/careers',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerCandidatesRoute = AppEmployerCandidatesRouteImport.update({
  id: '/employer/candidates',
  path: '/employer/candidates',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployerAnalyticsRoute = AppEmployerAnalyticsRouteImport.update({
  id: '/employer/analytics',
  path: '/employer/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateResumeRoute = AppCandidateResumeRouteImport.update({
  id: '/candidate/resume',
  path: '/candidate/resume',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatePortfolioRoute = AppCandidatePortfolioRouteImport.update({
  id: '/candidate/portfolio',
  path: '/candidate/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateOnboardingRoute = AppCandidateOnboardingRouteImport.update({
  id: '/candidate/onboarding',
  path: '/candidate/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateNotificationsRoute =
  AppCandidateNotificationsRouteImport.update({
    id: '/candidate/notifications',
    path: '/candidate/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppCandidateJobsRoute = AppCandidateJobsRouteImport.update({
  id: '/candidate/jobs',
  path: '/candidate/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateJobHuntRoute = AppCandidateJobHuntRouteImport.update({
  id: '/candidate/job-hunt',
  path: '/candidate/job-hunt',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateInterviewRoute = AppCandidateInterviewRouteImport.update({
  id: '/candidate/interview',
  path: '/candidate/interview',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateExternalRoute = AppCandidateExternalRouteImport.update({
  id: '/candidate/external',
  path: '/candidate/external',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateCoverLetterRoute = AppCandidateCoverLetterRouteImport.update({
  id: '/candidate/cover-letter',
  path: '/candidate/cover-letter',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateCareersRoute = AppCandidateCareersRouteImport.update({
  id: '/candidate/careers',
  path: '/candidate/careers',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateAssistantRoute = AppCandidateAssistantRouteImport.update({
  id: '/candidate/assistant',
  path: '/candidate/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidateApplicationsRoute =
  AppCandidateApplicationsRouteImport.update({
    id: '/candidate/applications',
    path: '/candidate/applications',
    getParentRoute: () => AppRoute,
  } as any)
const AppEmployerJobsIndexRoute = AppEmployerJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEmployerJobsRoute,
} as any)
const AppEmployerJobsNewRoute = AppEmployerJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppEmployerJobsRoute,
} as any)
const AppEmployerJobsJobIdRoute = AppEmployerJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AppEmployerJobsRoute,
} as any)
const AppCandidateTrainingSessionIdRoute =
  AppCandidateTrainingSessionIdRouteImport.update({
    id: '/candidate/training/$sessionId',
    path: '/candidate/training/$sessionId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/signup': typeof AuthSignupRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/share/$jobId': typeof ShareJobIdRoute
  '/candidate/applications': typeof AppCandidateApplicationsRoute
  '/candidate/assistant': typeof AppCandidateAssistantRoute
  '/candidate/careers': typeof AppCandidateCareersRoute
  '/candidate/cover-letter': typeof AppCandidateCoverLetterRoute
  '/candidate/external': typeof AppCandidateExternalRoute
  '/candidate/interview': typeof AppCandidateInterviewRoute
  '/candidate/job-hunt': typeof AppCandidateJobHuntRoute
  '/candidate/jobs': typeof AppCandidateJobsRoute
  '/candidate/notifications': typeof AppCandidateNotificationsRoute
  '/candidate/onboarding': typeof AppCandidateOnboardingRoute
  '/candidate/portfolio': typeof AppCandidatePortfolioRoute
  '/candidate/resume': typeof AppCandidateResumeRoute
  '/employer/analytics': typeof AppEmployerAnalyticsRoute
  '/employer/candidates': typeof AppEmployerCandidatesRoute
  '/employer/careers': typeof AppEmployerCareersRoute
  '/employer/jobs': typeof AppEmployerJobsRouteWithChildren
  '/employer/offers': typeof AppEmployerOffersRoute
  '/employer/talent-pool': typeof AppEmployerTalentPoolRoute
  '/employer/templates': typeof AppEmployerTemplatesRoute
  '/candidate/': typeof AppCandidateIndexRoute
  '/employer/': typeof AppEmployerIndexRoute
  '/candidate/training/$sessionId': typeof AppCandidateTrainingSessionIdRoute
  '/employer/jobs/$jobId': typeof AppEmployerJobsJobIdRoute
  '/employer/jobs/new': typeof AppEmployerJobsNewRoute
  '/employer/jobs/': typeof AppEmployerJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/signup': typeof AuthSignupRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/share/$jobId': typeof ShareJobIdRoute
  '/candidate/applications': typeof AppCandidateApplicationsRoute
  '/candidate/assistant': typeof AppCandidateAssistantRoute
  '/candidate/careers': typeof AppCandidateCareersRoute
  '/candidate/cover-letter': typeof AppCandidateCoverLetterRoute
  '/candidate/external': typeof AppCandidateExternalRoute
  '/candidate/interview': typeof AppCandidateInterviewRoute
  '/candidate/job-hunt': typeof AppCandidateJobHuntRoute
  '/candidate/jobs': typeof AppCandidateJobsRoute
  '/candidate/notifications': typeof AppCandidateNotificationsRoute
  '/candidate/onboarding': typeof AppCandidateOnboardingRoute
  '/candidate/portfolio': typeof AppCandidatePortfolioRoute
  '/candidate/resume': typeof AppCandidateResumeRoute
  '/employer/analytics': typeof AppEmployerAnalyticsRoute
  '/employer/candidates': typeof AppEmployerCandidatesRoute
  '/employer/careers': typeof AppEmployerCareersRoute
  '/employer/offers': typeof AppEmployerOffersRoute
  '/employer/talent-pool': typeof AppEmployerTalentPoolRoute
  '/employer/templates': typeof AppEmployerTemplatesRoute
  '/candidate': typeof AppCandidateIndexRoute
  '/employer': typeof AppEmployerIndexRoute
  '/candidate/training/$sessionId': typeof AppCandidateTrainingSessionIdRoute
  '/employer/jobs/$jobId': typeof AppEmployerJobsJobIdRoute
  '/employer/jobs/new': typeof AppEmployerJobsNewRoute
  '/employer/jobs': typeof AppEmployerJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/role': typeof AuthRoleRoute
  '/auth/signup': typeof AuthSignupRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/share/$jobId': typeof ShareJobIdRoute
  '/_app/candidate/applications': typeof AppCandidateApplicationsRoute
  '/_app/candidate/assistant': typeof AppCandidateAssistantRoute
  '/_app/candidate/careers': typeof AppCandidateCareersRoute
  '/_app/candidate/cover-letter': typeof AppCandidateCoverLetterRoute
  '/_app/candidate/external': typeof AppCandidateExternalRoute
  '/_app/candidate/interview': typeof AppCandidateInterviewRoute
  '/_app/candidate/job-hunt': typeof AppCandidateJobHuntRoute
  '/_app/candidate/jobs': typeof AppCandidateJobsRoute
  '/_app/candidate/notifications': typeof AppCandidateNotificationsRoute
  '/_app/candidate/onboarding': typeof AppCandidateOnboardingRoute
  '/_app/candidate/portfolio': typeof AppCandidatePortfolioRoute
  '/_app/candidate/resume': typeof AppCandidateResumeRoute
  '/_app/employer/analytics': typeof AppEmployerAnalyticsRoute
  '/_app/employer/candidates': typeof AppEmployerCandidatesRoute
  '/_app/employer/careers': typeof AppEmployerCareersRoute
  '/_app/employer/jobs': typeof AppEmployerJobsRouteWithChildren
  '/_app/employer/offers': typeof AppEmployerOffersRoute
  '/_app/employer/talent-pool': typeof AppEmployerTalentPoolRoute
  '/_app/employer/templates': typeof AppEmployerTemplatesRoute
  '/_app/candidate/': typeof AppCandidateIndexRoute
  '/_app/employer/': typeof AppEmployerIndexRoute
  '/_app/candidate/training/$sessionId': typeof AppCandidateTrainingSessionIdRoute
  '/_app/employer/jobs/$jobId': typeof AppEmployerJobsJobIdRoute
  '/_app/employer/jobs/new': typeof AppEmployerJobsNewRoute
  '/_app/employer/jobs/': typeof AppEmployerJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/chat'
    | '/api/generate'
    | '/api/transcribe'
    | '/auth/login'
    | '/auth/role'
    | '/auth/signup'
    | '/legal/privacy'
    | '/legal/terms'
    | '/share/$jobId'
    | '/candidate/applications'
    | '/candidate/assistant'
    | '/candidate/careers'
    | '/candidate/cover-letter'
    | '/candidate/external'
    | '/candidate/interview'
    | '/candidate/job-hunt'
    | '/candidate/jobs'
    | '/candidate/notifications'
    | '/candidate/onboarding'
    | '/candidate/portfolio'
    | '/candidate/resume'
    | '/employer/analytics'
    | '/employer/candidates'
    | '/employer/careers'
    | '/employer/jobs'
    | '/employer/offers'
    | '/employer/talent-pool'
    | '/employer/templates'
    | '/candidate/'
    | '/employer/'
    | '/candidate/training/$sessionId'
    | '/employer/jobs/$jobId'
    | '/employer/jobs/new'
    | '/employer/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/chat'
    | '/api/generate'
    | '/api/transcribe'
    | '/auth/login'
    | '/auth/role'
    | '/auth/signup'
    | '/legal/privacy'
    | '/legal/terms'
    | '/share/$jobId'
    | '/candidate/applications'
    | '/candidate/assistant'
    | '/candidate/careers'
    | '/candidate/cover-letter'
    | '/candidate/external'
    | '/candidate/interview'
    | '/candidate/job-hunt'
    | '/candidate/jobs'
    | '/candidate/notifications'
    | '/candidate/onboarding'
    | '/candidate/portfolio'
    | '/candidate/resume'
    | '/employer/analytics'
    | '/employer/candidates'
    | '/employer/careers'
    | '/employer/offers'
    | '/employer/talent-pool'
    | '/employer/templates'
    | '/candidate'
    | '/employer'
    | '/candidate/training/$sessionId'
    | '/employer/jobs/$jobId'
    | '/employer/jobs/new'
    | '/employer/jobs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/settings'
    | '/api/chat'
    | '/api/generate'
    | '/api/transcribe'
    | '/auth/login'
    | '/auth/role'
    | '/auth/signup'
    | '/legal/privacy'
    | '/legal/terms'
    | '/share/$jobId'
    | '/_app/candidate/applications'
    | '/_app/candidate/assistant'
    | '/_app/candidate/careers'
    | '/_app/candidate/cover-letter'
    | '/_app/candidate/external'
    | '/_app/candidate/interview'
    | '/_app/candidate/job-hunt'
    | '/_app/candidate/jobs'
    | '/_app/candidate/notifications'
    | '/_app/candidate/onboarding'
    | '/_app/candidate/portfolio'
    | '/_app/candidate/resume'
    | '/_app/employer/analytics'
    | '/_app/employer/candidates'
    | '/_app/employer/careers'
    | '/_app/employer/jobs'
    | '/_app/employer/offers'
    | '/_app/employer/talent-pool'
    | '/_app/employer/templates'
    | '/_app/candidate/'
    | '/_app/employer/'
    | '/_app/candidate/training/$sessionId'
    | '/_app/employer/jobs/$jobId'
    | '/_app/employer/jobs/new'
    | '/_app/employer/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRoleRoute: typeof AuthRoleRoute
  AuthSignupRoute: typeof AuthSignupRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ShareJobIdRoute: typeof ShareJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$jobId': {
      id: '/share/$jobId'
      path: '/share/$jobId'
      fullPath: '/share/$jobId'
      preLoaderRoute: typeof ShareJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/role': {
      id: '/auth/role'
      path: '/auth/role'
      fullPath: '/auth/role'
      preLoaderRoute: typeof AuthRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employer/': {
      id: '/_app/employer/'
      path: '/employer'
      fullPath: '/employer/'
      preLoaderRoute: typeof AppEmployerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/': {
      id: '/_app/candidate/'
      path: '/candidate'
      fullPath: '/candidate/'
      preLoaderRoute: typeof AppCandidateIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employer/templates': {
      id: '/_app/employer/templates'
      path: '/employer/templates'
      fullPath: '/employer/templates'
      preLoaderRoute: typeof AppEmployerTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employer/talent-pool': {
      id: '/_app/employer/talent-pool'
      path: '/employer/talent-pool'
      fullPath: '/employer/talent-pool'
      preLoaderRoute: typeof AppEmployerTalentPoolRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employer/offers': {
      id: '/_app/employer/offers'
      path: '/employer/offers'
      fullPath: '/employer/offers'
      preLoaderRoute: typeof AppEmployerOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employer/jobs': {
      id: '/_app/employer/jobs'
      path: '/employer/jobs'
      fullPath: '/employer/jobs'
      preLoaderRoute: typeof AppEmployerJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employer/careers': {
      id: '/_app/employer/careers'
      path: '/employer/careers'
      fullPath: '/employer/careers'
      preLoaderRoute: typeof AppEmployerCareersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employer/candidates': {
      id: '/_app/employer/candidates'
      path: '/employer/candidates'
      fullPath: '/employer/candidates'
      preLoaderRoute: typeof AppEmployerCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employer/analytics': {
      id: '/_app/employer/analytics'
      path: '/employer/analytics'
      fullPath: '/employer/analytics'
      preLoaderRoute: typeof AppEmployerAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/resume': {
      id: '/_app/candidate/resume'
      path: '/candidate/resume'
      fullPath: '/candidate/resume'
      preLoaderRoute: typeof AppCandidateResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/portfolio': {
      id: '/_app/candidate/portfolio'
      path: '/candidate/portfolio'
      fullPath: '/candidate/portfolio'
      preLoaderRoute: typeof AppCandidatePortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/onboarding': {
      id: '/_app/candidate/onboarding'
      path: '/candidate/onboarding'
      fullPath: '/candidate/onboarding'
      preLoaderRoute: typeof AppCandidateOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/notifications': {
      id: '/_app/candidate/notifications'
      path: '/candidate/notifications'
      fullPath: '/candidate/notifications'
      preLoaderRoute: typeof AppCandidateNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/jobs': {
      id: '/_app/candidate/jobs'
      path: '/candidate/jobs'
      fullPath: '/candidate/jobs'
      preLoaderRoute: typeof AppCandidateJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/job-hunt': {
      id: '/_app/candidate/job-hunt'
      path: '/candidate/job-hunt'
      fullPath: '/candidate/job-hunt'
      preLoaderRoute: typeof AppCandidateJobHuntRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/interview': {
      id: '/_app/candidate/interview'
      path: '/candidate/interview'
      fullPath: '/candidate/interview'
      preLoaderRoute: typeof AppCandidateInterviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/external': {
      id: '/_app/candidate/external'
      path: '/candidate/external'
      fullPath: '/candidate/external'
      preLoaderRoute: typeof AppCandidateExternalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/cover-letter': {
      id: '/_app/candidate/cover-letter'
      path: '/candidate/cover-letter'
      fullPath: '/candidate/cover-letter'
      preLoaderRoute: typeof AppCandidateCoverLetterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/careers': {
      id: '/_app/candidate/careers'
      path: '/candidate/careers'
      fullPath: '/candidate/careers'
      preLoaderRoute: typeof AppCandidateCareersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/assistant': {
      id: '/_app/candidate/assistant'
      path: '/candidate/assistant'
      fullPath: '/candidate/assistant'
      preLoaderRoute: typeof AppCandidateAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidate/applications': {
      id: '/_app/candidate/applications'
      path: '/candidate/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof AppCandidateApplicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employer/jobs/': {
      id: '/_app/employer/jobs/'
      path: '/'
      fullPath: '/employer/jobs/'
      preLoaderRoute: typeof AppEmployerJobsIndexRouteImport
      parentRoute: typeof AppEmployerJobsRoute
    }
    '/_app/employer/jobs/new': {
      id: '/_app/employer/jobs/new'
      path: '/new'
      fullPath: '/employer/jobs/new'
      preLoaderRoute: typeof AppEmployerJobsNewRouteImport
      parentRoute: typeof AppEmployerJobsRoute
    }
    '/_app/employer/jobs/$jobId': {
      id: '/_app/employer/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/employer/jobs/$jobId'
      preLoaderRoute: typeof AppEmployerJobsJobIdRouteImport
      parentRoute: typeof AppEmployerJobsRoute
    }
    '/_app/candidate/training/$sessionId': {
      id: '/_app/candidate/training/$sessionId'
      path: '/candidate/training/$sessionId'
      fullPath: '/candidate/training/$sessionId'
      preLoaderRoute: typeof AppCandidateTrainingSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppEmployerJobsRouteChildren {
  AppEmployerJobsJobIdRoute: typeof AppEmployerJobsJobIdRoute
  AppEmployerJobsNewRoute: typeof AppEmployerJobsNewRoute
  AppEmployerJobsIndexRoute: typeof AppEmployerJobsIndexRoute
}

const AppEmployerJobsRouteChildren: AppEmployerJobsRouteChildren = {
  AppEmployerJobsJobIdRoute: AppEmployerJobsJobIdRoute,
  AppEmployerJobsNewRoute: AppEmployerJobsNewRoute,
  AppEmployerJobsIndexRoute: AppEmployerJobsIndexRoute,
}

const AppEmployerJobsRouteWithChildren = AppEmployerJobsRoute._addFileChildren(
  AppEmployerJobsRouteChildren,
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppCandidateApplicationsRoute: typeof AppCandidateApplicationsRoute
  AppCandidateAssistantRoute: typeof AppCandidateAssistantRoute
  AppCandidateCareersRoute: typeof AppCandidateCareersRoute
  AppCandidateCoverLetterRoute: typeof AppCandidateCoverLetterRoute
  AppCandidateExternalRoute: typeof AppCandidateExternalRoute
  AppCandidateInterviewRoute: typeof AppCandidateInterviewRoute
  AppCandidateJobHuntRoute: typeof AppCandidateJobHuntRoute
  AppCandidateJobsRoute: typeof AppCandidateJobsRoute
  AppCandidateNotificationsRoute: typeof AppCandidateNotificationsRoute
  AppCandidateOnboardingRoute: typeof AppCandidateOnboardingRoute
  AppCandidatePortfolioRoute: typeof AppCandidatePortfolioRoute
  AppCandidateResumeRoute: typeof AppCandidateResumeRoute
  AppEmployerAnalyticsRoute: typeof AppEmployerAnalyticsRoute
  AppEmployerCandidatesRoute: typeof AppEmployerCandidatesRoute
  AppEmployerCareersRoute: typeof AppEmployerCareersRoute
  AppEmployerJobsRoute: typeof AppEmployerJobsRouteWithChildren
  AppEmployerOffersRoute: typeof AppEmployerOffersRoute
  AppEmployerTalentPoolRoute: typeof AppEmployerTalentPoolRoute
  AppEmployerTemplatesRoute: typeof AppEmployerTemplatesRoute
  AppCandidateIndexRoute: typeof AppCandidateIndexRoute
  AppEmployerIndexRoute: typeof AppEmployerIndexRoute
  AppCandidateTrainingSessionIdRoute: typeof AppCandidateTrainingSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppCandidateApplicationsRoute: AppCandidateApplicationsRoute,
  AppCandidateAssistantRoute: AppCandidateAssistantRoute,
  AppCandidateCareersRoute: AppCandidateCareersRoute,
  AppCandidateCoverLetterRoute: AppCandidateCoverLetterRoute,
  AppCandidateExternalRoute: AppCandidateExternalRoute,
  AppCandidateInterviewRoute: AppCandidateInterviewRoute,
  AppCandidateJobHuntRoute: AppCandidateJobHuntRoute,
  AppCandidateJobsRoute: AppCandidateJobsRoute,
  AppCandidateNotificationsRoute: AppCandidateNotificationsRoute,
  AppCandidateOnboardingRoute: AppCandidateOnboardingRoute,
  AppCandidatePortfolioRoute: AppCandidatePortfolioRoute,
  AppCandidateResumeRoute: AppCandidateResumeRoute,
  AppEmployerAnalyticsRoute: AppEmployerAnalyticsRoute,
  AppEmployerCandidatesRoute: AppEmployerCandidatesRoute,
  AppEmployerCareersRoute: AppEmployerCareersRoute,
  AppEmployerJobsRoute: AppEmployerJobsRouteWithChildren,
  AppEmployerOffersRoute: AppEmployerOffersRoute,
  AppEmployerTalentPoolRoute: AppEmployerTalentPoolRoute,
  AppEmployerTemplatesRoute: AppEmployerTemplatesRoute,
  AppCandidateIndexRoute: AppCandidateIndexRoute,
  AppEmployerIndexRoute: AppEmployerIndexRoute,
  AppCandidateTrainingSessionIdRoute: AppCandidateTrainingSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRoleRoute: AuthRoleRoute,
  AuthSignupRoute: AuthSignupRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ShareJobIdRoute: ShareJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
